#!/usr/bin/ruby

ONE_LOCATION=ENV["ONE_LOCATION"]

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby"
    VAR_LOCATION = "/var/lib/one"
    LIB_LOCATION = "/usr/lib/one"
    ETC_LOCATION = "/etc/one"
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby"
    VAR_LOCATION = ONE_LOCATION+"/var"
    LIB_LOCATION = ONE_LOCATION+"/lib"
    ETC_LOCATION = ONE_LOCATION + "/etc"
end

$: << RUBY_LIB_LOCATION
$: << RUBY_LIB_LOCATION+"/cloud" # For the Repository Manager
$: << RUBY_LIB_LOCATION+"/cli" # For the Repository Manager
$: << LIB_LOCATION+'/oneflow/lib'

################################################
# Required libraries
################################################
require 'yaml'
require 'erb'
require 'tempfile'
require 'fileutils'
require 'json'

require 'opennebula'
include OpenNebula

require 'pp'

if ENV['ONE_AUTH']
    authfile = ENV['ONE_AUTH']
else
    authfile = "#{ENV['HOME']}/.one/one_auth"
end

# OpenNebula credentials
CREDENTIALS = File.read(authfile).strip

# XML_RPC endpoint where OpenNebula is listening
ENDPOINT    = "http://localhost:2633/RPC2"

@client = Client.new(CREDENTIALS, ENDPOINT)

version = ">= 0"
gem 'pry', version
load Gem.bin_path('pry', 'pry', version)
