#!/bin/bash

if [ "$1" = "--tail" -o "$1" == "-f" ]; then
    shift
    PAGER="tail -f"
else
    PAGER=${PAGER:-less}
fi


if [ -n "$ONE_LOCATION" ]; then
    if [ -n "$1" ]; then
        case "$1" in
        econe)
            $PAGER $ONE_LOCATION/var/econe-server.log
            ;;
        econe.error)
            $PAGER $ONE_LOCATION/var/econe-server.error
            ;;
        sunstone)
            $PAGER $ONE_LOCATION/var/sunstone.log
            ;;
        sunstone.error)
            $PAGER $ONE_LOCATION/var/sunstone.error
            ;;
        sched)
            $PAGER $ONE_LOCATION/var/sched.log
            ;;
        monitor)
            $PAGER $ONE_LOCATION/var/monitor.log
            ;;
        fireedge)
            $PAGER $ONE_LOCATION/var/fireedge.log
            ;;
        fireedgerr)
            $PAGER $ONE_LOCATION/var/fireedge.error
            ;;
        *)
            $PAGER $ONE_LOCATION/var/vms/$1/vm.log
            ;;
        esac
    else
        $PAGER $ONE_LOCATION/var/oned.log
    fi
else
    if [ -n "$1" ]; then
        case "$1" in
        econe)
            $PAGER /var/log/one/econe-server.log
            ;;
        econe.error)
            $PAGER /var/log/one/econe-server.error
            ;;
        sunstone)
            $PAGER /var/log/one/sunstone.log
            ;;
        sunstone.error)
            $PAGER /var/log/one/sunstone.error
            ;;
        sched)
            $PAGER /var/log/one/sched.log
            ;;
        monitor)
            $PAGER /var/log/one/monitor.log
            ;;
        fireedge)
            $PAGER /var/log/one/fireedge.log
            ;;
        fireedgerr)
            $PAGER /var/log/one/fireedge.err
            ;;
        *)
            $PAGER /var/log/one/$1.log
            ;;
        esac
    else
        $PAGER /var/log/one/oned.log
    fi
fi
