#!/bin/bash

PAGER=${PAGER:-less}

if [ -n "$ONE_LOCATION" ]; then
    if [ -n "$1" ]; then
        $PAGER $ONE_LOCATION/var/$1/vm.log
    else
        $PAGER $ONE_LOCATION/var/oned.log
    fi
else
    if [ -n "$1" ]; then
        $PAGER /var/log/one/$1.log
    else
        $PAGER /var/log/one/oned.log
    fi
fi
