#!/bin/bash

if [ -n "$ONE_LOCATION" ]; then
    if [ -n "$1" ]; then
        less $ONE_LOCATION/var/$1/vm.log
    else
        less $ONE_LOCATION/var/oned.log
    fi
else
    if [ -n "$1" ]; then
        less /var/log/one/$1.log
    else
        less /var/log/one/oned.log
    fi
fi
