#!/usr/bin/ruby

ONE_LOCATION=ENV["ONE_LOCATION"]

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby"
    VAR_LOCATION = "/var/lib/one"
    LIB_LOCATION = "/usr/lib/one"
    ETC_LOCATION = "/etc/one"
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby"
    VAR_LOCATION = ONE_LOCATION+"/var"
    LIB_LOCATION = ONE_LOCATION+"/lib"
    ETC_LOCATION = ONE_LOCATION + "/etc"
end

$: << RUBY_LIB_LOCATION
$: << RUBY_LIB_LOCATION+"/cloud"
$: << RUBY_LIB_LOCATION+"/cli"

################################################
# Required libraries
################################################
require 'opennebula'
include OpenNebula

require 'pp'

client = Client.new

ssh_public_key = File.read("#{ENV['HOME']}/.ssh/id_rsa.pub").strip

user = User.new_with_id(OpenNebula::User::SELF, client)
user.info
rc = user.update(%Q{SSH_PUBLIC_KEY="#{ssh_public_key}"}, true)
if OpenNebula.is_error?(rc)
    STDERR.puts rc.message
    exit 1
end
